# Generated by Django 6.0.2 on 2026-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a_score', models.IntegerField(null=True)),
                ('team_b_score', models.IntegerField(null=True)),
            ],
        ),
    ]
